#include "Application.hpp"
#include <filesystem>
#include "ui/frame/settings/AppAdvanced.hpp"
#include "utils/FS.hpp"

namespace Frame::Settings {
    AppAdvanced::AppAdvanced(Main::Application * a) : Frame(a) {
        // Temporary variables
        Config * cfg = this->app->config();
        Aether::ListOption * opt;

        // Advanced::auto_launch_service
        this->addToggle("Auto Launch Sysmodule", [cfg]() -> bool {
            return cfg->autoLaunchService();
        }, [cfg](bool b) {
            cfg->setAutoLaunchService(b);
        });
        this->addComment("Automatically attempt to start the sysmodule if it is not running when the app is launched.");
        this->list->addElement(new Aether::ListSeparator());

        // Remove redundant images
        this->addButton("Remove Unneeded Images", [this]() {
            this->removeImages();
        });
        this->addComment("Remove any images within '/switch/TriPlayer/images' that are no longer needed. TriPlayer aims to keep this folder clean and up-to-date so this shouldn't remove any files under normal circumstances.");
        this->list->addElement(new Aether::ListSeparator());

        // Advanced::set_queue_max
        opt = new Aether::ListOption("Initial Queue Size", std::to_string(cfg->setQueueMax()), nullptr);
        opt->setCallback([this, cfg, opt]() {
            int val = cfg->setQueueMax();
            if (this->getNumberInput(val, "Initial Queue Size", "", true)) {
                val = (val < -1 ? -1 : (val > 65535 ? 65535 : val));
                if (cfg->setSetQueueMax(val)) {
                    opt->setValue(std::to_string(val));
                    this->app->sysmodule()->setQueueLimit(val);
                }
            }
        });
        opt->setColours(this->app->theme()->muted2(), this->app->theme()->FG(), this->app->theme()->accent());
        this->list->addElement(opt);
        this->addComment("Number of songs to create a queue with when playing a song/album/etc. A negative number indicates no limit.");
        this->list->addElement(new Aether::ListSeparator());

        // Advanced::search_max_phrases
        opt = new Aether::ListOption("Maximum Search Phrases", std::to_string(cfg->searchMaxPhrases()), nullptr);
        opt->setCallback([this, cfg, opt]() {
            int val = cfg->searchMaxPhrases();
            if (this->getNumberInput(val, "Maximum Search Phrases", "", false)) {
                val = (val < 1 ? 1 : val);
                if (cfg->setSearchMaxPhrases(val)) {
                    opt->setValue(std::to_string(val));
                    this->app->database()->setSearchPhraseCount(val);
                }
            }
        });
        opt->setColours(this->app->theme()->muted2(), this->app->theme()->FG(), this->app->theme()->accent());
        this->list->addElement(opt);
        this->addComment("The maximum number of 'phrases' to search with. Phrases are generated by swapping out words from the query with those found in your library. A larger number will result in a 'wider' search, which may take longer. This has a default value of 8, and can not be set to 0.");

        // Advanced::search_max_score
        opt = new Aether::ListOption("Maximum Search Score", std::to_string(cfg->searchMaxScore()), nullptr);
        opt->setCallback([this, cfg, opt]() {
            int val = cfg->searchMaxScore();
            if (this->getNumberInput(val, "Maximum Search Score", "", false)) {
                val = (val < 30 ? 30 : val);
                if (cfg->setSearchMaxScore(val)) {
                    opt->setValue(std::to_string(val));
                    this->app->database()->setSpellfixScore(val);
                }
            }
        });
        opt->setColours(this->app->theme()->muted2(), this->app->theme()->FG(), this->app->theme()->accent());
        this->list->addElement(opt);
        this->addComment("The maximum 'score' a potential result can have to be considered relevant. A score is calculated by determining how similar the title, artist, etc. is to the search query. A larger number will result in more results that are less relevant, but also better results for misspelled words. This has a default value of 130, and cannot be smaller than 30.");
    }

    void AppAdvanced::removeImages() {
        // Get list of all images referenced in database (returned in order)
        bool ok;
        std::vector<std::string> dbFiles = this->app->database()->getAllImagePaths(ok);
        if (!ok) {
            return;
        }

        // Get list of all files in folder
        std::vector<std::string> folderFiles;
        for (auto & entry: std::filesystem::recursive_directory_iterator("/switch/TriPlayer/images/")) {
            if (entry.is_directory()) {
                continue;
            }

            folderFiles.push_back(entry.path());
        }
        std::sort(folderFiles.begin(), folderFiles.end());

        // Remove from folder where not in DB
        for (size_t i = 0; i < folderFiles.size(); i++) {
            bool inDB = std::binary_search(dbFiles.begin(), dbFiles.end(), folderFiles[i]);
            if (!inDB) {
                Utils::Fs::deleteFile(folderFiles[i]);
            }
        }
    }
};